{% set name = "dsc" %}
{% set version = "0.4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db5c1b5d393e144c21e7c50472d9fa446c3230739a056c20a7967d247fbe5de4

build:
  noarch: python
  number: 0
  entry_points:
    - dsc = dsc.__main__:main
    - dsc-query = dsc.__query__:main
    - dsc-io = dsc.dsc_io:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py
    - msgpack-python
    - numexpr
    - numpy
    - pandas >=0.24.1
    - ptable
    - pyarrow >=0.5.0
    - python >=3.6
    - sos >=0.19.7
    - sos-pbs >=0.19.6
    - sqlalchemy
    - sympy
    - tzlocal

test:
  imports:
    - dsc
    - dsc.parser
  commands:
    - dsc --help
    - dsc-query --help
    - dsc-io --help

about:
  home: https://github.com/stephenslab/dsc
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Implementation of Dynamic Statistical Comparisons
  doc_url: https://stephenslab.github.io/dsc-wiki/

extra:
  recipe-maintainers:
    - gaow
    - jdblischak
