travis:
  secure:
    BINSTAR_TOKEN: g6nHjpvIWn8EB77Whhsk7y78cYC2QpLcuD/cJUbhge67tEe4OmGMqu76g52Pbg2zAfEjKbd3KEUXzXSrbaQGsy54JWd4mgHrduDCcxok9FonhT/6rZduKeAXU5Z246yauSarzDCNimpV0aXSI6CE/97olHm5G+akeS2PIPHnJ3BmwlC/e/V9tj2xsDcUNLE/OdjC9KyjAc6ieETQMwUUPXQjdzyYUXuXFemFH5XLENshFyszfG6KLtVVVsg/3KZX4lW13e4vTdw6yDTkz/xpbYBpy99IjxuXpk8QwQgGADRujIgCyZn36+v96r9HzghGlVmYtpLf2CIgjVkQ+iATshVb6dHyLxXC0Q//+0Ak/zcP1BKTg6JmsOiDbZ28koL1noCUXD9LkEJ9KZabaSMqCOwW+uE6NNwEKzFmzZ/5Jh06TXcPJiEbUluJqC9hq1wQ7lp+JgpZa0VeoRyOAbkcFpgkXG3P0qQTJXePcgXTPGMT6ae6aqEa0c7hbH41wbNq4YuqJON/kDDNvNuni40vKLpiDJhmgcJZT40fpdMJDYfzTq6wPfd2Z4EcBueNU9B7OQh7SaMbKX7XTai9ABItJ6AdGiCNAVLiXZSDEfjujyBSqTeCOSu0UntUuGCfTu7T8heRv00MFWqtORVrsREwHfpEeZOLFYRGTIseYcWPz64=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
